# Generated by Django 3.1.7 on 2021-03-01 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bigapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweetitem',
            old_name='dt_filed',
            new_name='dt_posted',
        ),
    ]
